[package]
name = "nft_marketplace"
version = "1.0.0"
authors = []

[addresses]
my_addrx="_"

[dev-addresses]
my_addrx="0x980"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
