[package]
name = "swap"
version = "1.0.0"
authors = []

[addresses]
addrx="_"
admin="_"

[dev-addresses]
addrx="0xCAFE"
admin="0x100"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
