[package]
name = "flip-or-nothing"
version = "1.0.0"
authors = []

[addresses]
game_host="_"

[dev-addresses]
game_host="0x100"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
