[package]
name = "staking-module"
version = "1.0.0"
authors = []

[addresses]
stake_addr="_"

[dev-addresses]
stake_addr="0xCAFE"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
